# Generated by Django 3.1.3 on 2020-11-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('free', models.IntegerField()),
                ('organizations', models.CharField(max_length=255)),
                ('data_start', models.DateTimeField()),
                ('data_end', models.DateTimeField()),
                ('age', models.IntegerField()),
            ],
        ),
    ]
