# Generated by Django 3.1.3 on 2020-11-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_groups_teachers_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groups',
            name='course',
        ),
        migrations.RemoveField(
            model_name='users',
            name='course',
        ),
    ]
