# Generated by Django 3.1.3 on 2020-11-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_auto_20201120_1644'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='teachers',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='fname',
            new_name='FCs',
        ),
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.CharField(default='teacher', max_length=255),
        ),
    ]
