# Generated by Django 3.1.3 on 2020-11-24 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_list_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FC', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('FCs', models.CharField(max_length=255)),
                ('name_work', models.CharField(max_length=255)),
                ('link_work', models.CharField(max_length=255)),
                ('error', models.CharField(max_length=255)),
                ('estimation', models.CharField(max_length=255)),
                ('nmae_item', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
    ]
